# Generated by Django 3.2.9 on 2022-01-02 17:36

from django.db import migrations, models
import django.db.models.deletion
import retaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Traditional', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='categories_food', to='retaurant.Category')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'وعده غذایی',
                'verbose_name_plural': 'وعده های غذایی',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to=retaurant.models.MenuItem.get_upload_path)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='retaurant.branch')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_foods', to='retaurant.food')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم های منو',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=0, default=100000, max_digits=8)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران ها',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'وضعیت سفارش',
                'verbose_name_plural': 'وضعیت های سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='retaurant.menuitem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='retaurant.order')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم های  سفارش',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='retaurant.status'),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(related_name='meals_food', to='retaurant.Meal'),
        ),
        migrations.AddField(
            model_name='branch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retaurant.category'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.manager'),
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchs', to='retaurant.restaurant'),
        ),
    ]
